//Teste de exceções
public class Excecao
{
 public static void main(String args[])
 { 
     int d=0;
     int a=0;
   try
   {
     System.out.println("Dentro do bloca de excecao");
   
     a=42/d;
   }catch(Exception e)
 {
   System.out.println("Err: "+ e);
         d = Entrada.leiaInt("Informe o valor");
 if (d > 0)
 {
           a=42/d;
        }
 }
 System.out.println("O valor final do a ="+a);
 }
}